railstutorial: "https://www.railstutorial.org/"
helppage: "https://www.railstutorial.org/help"
railsbook: "https://www.railstutorial.org/book"
learnenough: "https://www.learnenough.com"
screencasts: "https://screencasts.railstutorial.org/"
rubyonrails: "https://rubyonrails.org/"
contact: "https://www.railstutorial.org/contact"
micheal_hartl: "https://www.michealhartl.com/"
news: "https://news.railstutorial.org/"
